version: '3'

volumes:
  db_volume:

networks:
  postgres_network:
    driver: bridge

services:
  web:
    build: .
    networks:
        - postgres_network
    depends_on:
       - database1
    volumes:
      - ./main.go:/main.go
    ports:
       - "8000:8000"

  database1:
    image: postgres:10-alpine
    volumes:
      - db_volume:/data/db
    networks:
       - postgres_network
    env_file:
       - .env
  adminer:
    image: adminer
    ports:
        - 8080:8080
    depends_on:
       - database1
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: database1
      ADMINER_DEFAULT_DB_NAME: database1
      ADMINER_DEFAULT_DB_USER: audrey_horne
      ADMINER_DEFAULT_DB_PASSWORD: my_love_to_audrey_is_enough_strong_to_be_a_password
      ADMINER_DESIGN: pepa-linha
    networks:
       - postgres_network
